/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DabbaBooking {
  'id' : string,
  'status' : DabbaStatusEnum,
  'pickupAddress' : string,
  'slotTime' : PickupSlotEnum,
  'customerId' : Principal,
  'frequency' : SubscriptionTypeEnum,
  'dropAddress' : string,
  'deliveryPartnerId' : [] | [Principal],
}
export type DabbaStatusEnum = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'inTransit' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export type Email = string;
export type OtpCode = string;
export type OtpStatus = { 'verified' : null } |
  { 'expired' : null } |
  { 'alreadyVerified' : null } |
  { 'invalidPhoneNumber' : null } |
  { 'invalid' : null } |
  { 'twilioMissing' : null } |
  { 'notFound' : null } |
  { 'delivered' : null } |
  { 'twilioResponse' : string } |
  { 'twilioError' : string } |
  { 'smsFailed' : string };
export type PhoneNumber = string;
export type PickupSlotEnum = { 'morning' : null } |
  { 'midMorning' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTypeEnum = { 'none' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TwilioConfiguration {
  'accountSid' : string,
  'authToken' : string,
  'fromNumber' : string,
}
export interface UserProfile { 'userType' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAssignedBookings' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isTwilioConfigured' : ActorMethod<[], boolean>,
  'linkEmailToProfile' : ActorMethod<[Email], undefined>,
  'linkPhoneToProfile' : ActorMethod<[PhoneNumber], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendEmailOtp' : ActorMethod<[Email], OtpStatus>,
  'sendPhoneOtp' : ActorMethod<[PhoneNumber], OtpStatus>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTwilioConfiguration' : ActorMethod<[TwilioConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'twilioTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBooking' : ActorMethod<[DabbaBooking], undefined>,
  'verifyEmailOtp' : ActorMethod<[Email, OtpCode], OtpStatus>,
  'verifyPhoneOtp' : ActorMethod<[PhoneNumber, OtpCode], OtpStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];