/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OtpCode = string;
export type Email = string;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type OtpStatus = {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "alreadyVerified";
    alreadyVerified: null;
} | {
    __kind__: "invalidPhoneNumber";
    invalidPhoneNumber: null;
} | {
    __kind__: "invalid";
    invalid: null;
} | {
    __kind__: "twilioMissing";
    twilioMissing: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "twilioResponse";
    twilioResponse: string;
} | {
    __kind__: "twilioError";
    twilioError: string;
} | {
    __kind__: "smsFailed";
    smsFailed: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type PhoneNumber = string;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface DabbaBooking {
    id: string;
    status: DabbaStatusEnum;
    pickupAddress: string;
    slotTime: PickupSlotEnum;
    customerId: Principal;
    frequency: SubscriptionTypeEnum;
    dropAddress: string;
    deliveryPartnerId?: Principal;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface TwilioConfiguration {
    accountSid: string;
    authToken: string;
    fromNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    userType: string;
    name: string;
}
export enum DabbaStatusEnum {
    cancelled = "cancelled",
    pending = "pending",
    inTransit = "inTransit",
    pickedUp = "pickedUp",
    delivered = "delivered"
}
export enum PickupSlotEnum {
    morning = "morning",
    midMorning = "midMorning"
}
export enum SubscriptionTypeEnum {
    none = "none",
    daily = "daily",
    weekly = "weekly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    getAssignedBookings(deliveryPartnerId: string): Promise<Array<string>>;
    getAllBookings(): Promise<Array<DabbaBooking>>;
    getCallerBookings(): Promise<Array<DabbaBooking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isTwilioConfigured(): Promise<boolean>;
    linkEmailToProfile(email: Email): Promise<void>;
    linkPhoneToProfile(phone: PhoneNumber): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendEmailOtp(email: Email): Promise<OtpStatus>;
    sendPhoneOtp(phone: PhoneNumber): Promise<OtpStatus>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setTwilioConfiguration(config: TwilioConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    twilioTransform(input: TransformationInput): Promise<TransformationOutput>;
    updateBooking(booking: DabbaBooking): Promise<void>;
    verifyEmailOtp(email: Email, otp: OtpCode): Promise<OtpStatus>;
    verifyPhoneOtp(phone: PhoneNumber, otp: OtpCode): Promise<OtpStatus>;
}
import type { DabbaBooking as _DabbaBooking, DabbaStatusEnum as _DabbaStatusEnum, OtpStatus as _OtpStatus, PickupSlotEnum as _PickupSlotEnum, StripeSessionStatus as _StripeSessionStatus, SubscriptionTypeEnum as _SubscriptionTypeEnum, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async getAssignedBookings(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedBookings(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<DabbaBooking>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getAllBookings();
                return result.map((b: any) => from_candid_record_n20_reverse(b));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getAllBookings();
            return result.map((b: any) => from_candid_record_n20_reverse(b));
        }
    }
    async getCallerBookings(): Promise<Array<DabbaBooking>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getCallerBookings();
                return result.map((b: any) => from_candid_record_n20_reverse(b));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).getCallerBookings();
            return result.map((b: any) => from_candid_record_n20_reverse(b));
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isTwilioConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTwilioConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTwilioConfigured();
            return result;
        }
    }
    async linkEmailToProfile(arg0: Email): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkEmailToProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkEmailToProfile(arg0);
            return result;
        }
    }
    async linkPhoneToProfile(arg0: PhoneNumber): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkPhoneToProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkPhoneToProfile(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendEmailOtp(arg0: Email): Promise<OtpStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.sendEmailOtp(arg0);
                return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendEmailOtp(arg0);
            return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendPhoneOtp(arg0: PhoneNumber): Promise<OtpStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPhoneOtp(arg0);
                return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPhoneOtp(arg0);
            return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setTwilioConfiguration(arg0: TwilioConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTwilioConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTwilioConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async twilioTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.twilioTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.twilioTransform(arg0);
            return result;
        }
    }
    async updateBooking(arg0: DabbaBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(to_candid_DabbaBooking_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(to_candid_DabbaBooking_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyEmailOtp(arg0: Email, arg1: OtpCode): Promise<OtpStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmailOtp(arg0, arg1);
                return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmailOtp(arg0, arg1);
            return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyPhoneOtp(arg0: PhoneNumber, arg1: OtpCode): Promise<OtpStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPhoneOtp(arg0, arg1);
                return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPhoneOtp(arg0, arg1);
            return from_candid_OtpStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_OtpStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OtpStatus): OtpStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n15(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    expired: null;
} | {
    alreadyVerified: null;
} | {
    invalidPhoneNumber: null;
} | {
    invalid: null;
} | {
    twilioMissing: null;
} | {
    notFound: null;
} | {
    delivered: null;
} | {
    twilioResponse: string;
} | {
    twilioError: string;
} | {
    smsFailed: string;
}): {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "alreadyVerified";
    alreadyVerified: null;
} | {
    __kind__: "invalidPhoneNumber";
    invalidPhoneNumber: null;
} | {
    __kind__: "invalid";
    invalid: null;
} | {
    __kind__: "twilioMissing";
    twilioMissing: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "twilioResponse";
    twilioResponse: string;
} | {
    __kind__: "twilioError";
    twilioError: string;
} | {
    __kind__: "smsFailed";
    smsFailed: string;
} {
    return "verified" in value ? {
        __kind__: "verified",
        verified: value.verified
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "alreadyVerified" in value ? {
        __kind__: "alreadyVerified",
        alreadyVerified: value.alreadyVerified
    } : "invalidPhoneNumber" in value ? {
        __kind__: "invalidPhoneNumber",
        invalidPhoneNumber: value.invalidPhoneNumber
    } : "invalid" in value ? {
        __kind__: "invalid",
        invalid: value.invalid
    } : "twilioMissing" in value ? {
        __kind__: "twilioMissing",
        twilioMissing: value.twilioMissing
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "delivered" in value ? {
        __kind__: "delivered",
        delivered: value.delivered
    } : "twilioResponse" in value ? {
        __kind__: "twilioResponse",
        twilioResponse: value.twilioResponse
    } : "twilioError" in value ? {
        __kind__: "twilioError",
        twilioError: value.twilioError
    } : "smsFailed" in value ? {
        __kind__: "smsFailed",
        smsFailed: value.smsFailed
    } : value;
}
function to_candid_DabbaBooking_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DabbaBooking): _DabbaBooking {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_DabbaStatusEnum_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DabbaStatusEnum): _DabbaStatusEnum {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PickupSlotEnum_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupSlotEnum): _PickupSlotEnum {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTypeEnum_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTypeEnum): _SubscriptionTypeEnum {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: DabbaStatusEnum;
    pickupAddress: string;
    slotTime: PickupSlotEnum;
    customerId: Principal;
    frequency: SubscriptionTypeEnum;
    dropAddress: string;
    deliveryPartnerId?: Principal;
}): {
    id: string;
    status: _DabbaStatusEnum;
    pickupAddress: string;
    slotTime: _PickupSlotEnum;
    customerId: Principal;
    frequency: _SubscriptionTypeEnum;
    dropAddress: string;
    deliveryPartnerId: [] | [Principal];
} {
    return {
        id: value.id,
        status: to_candid_DabbaStatusEnum_n21(_uploadFile, _downloadFile, value.status),
        pickupAddress: value.pickupAddress,
        slotTime: to_candid_PickupSlotEnum_n23(_uploadFile, _downloadFile, value.slotTime),
        customerId: value.customerId,
        frequency: to_candid_SubscriptionTypeEnum_n25(_uploadFile, _downloadFile, value.frequency),
        dropAddress: value.dropAddress,
        deliveryPartnerId: value.deliveryPartnerId ? candid_some(value.deliveryPartnerId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DabbaStatusEnum): {
    cancelled: null;
} | {
    pending: null;
} | {
    inTransit: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} {
    return value == DabbaStatusEnum.cancelled ? {
        cancelled: null
    } : value == DabbaStatusEnum.pending ? {
        pending: null
    } : value == DabbaStatusEnum.inTransit ? {
        inTransit: null
    } : value == DabbaStatusEnum.pickedUp ? {
        pickedUp: null
    } : value == DabbaStatusEnum.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PickupSlotEnum): {
    morning: null;
} | {
    midMorning: null;
} {
    return value == PickupSlotEnum.morning ? {
        morning: null
    } : value == PickupSlotEnum.midMorning ? {
        midMorning: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTypeEnum): {
    none: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == SubscriptionTypeEnum.none ? {
        none: null
    } : value == SubscriptionTypeEnum.daily ? {
        daily: null
    } : value == SubscriptionTypeEnum.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function from_candid_record_n20_reverse(value: any): DabbaBooking {
    return {
        id: value.id,
        status: value.status.__kind__ as any,
        pickupAddress: value.pickupAddress,
        slotTime: value.slotTime.__kind__ as any,
        customerId: value.customerId,
        frequency: value.frequency.__kind__ as any,
        dropAddress: value.dropAddress,
        deliveryPartnerId: value.deliveryPartnerId && value.deliveryPartnerId.length > 0 ? value.deliveryPartnerId[0] : undefined,
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
